#!/bin/bash

pkglist=$HOME/.setup/aur-pkglist
tmp=.tmp

if [ -z "$1" ]; then
    echo "Please specify at least one package"
else
    for package in "$@"; do
        yay -S $package --noconfirm --needed
        if [ $? -ne 0 ]; then
            echo "$package not found or failed while installing"
        else
            grep -x $package $pkglist
            if [ $? -ne 0 ]; then
                echo $package >> $pkglist
                sort $pkglist > $pkglist$tmp
                mv $pkglist$tmp $pkglist
                echo "$package installed and added to pkglist"
            else
                echo "$package already in pkglist"
            fi
        fi
    done
fi

