#!/bin/bash
# Set the brightness of the display.

# Find the correct backlight device ( if one exists )

for directory in /sys/class/backlight/*; do
    backlight_path=$directory
    echo $backlight_path
done

if [[ -z "$backlight_path" ]]; then
    echo "No backlight found"
    exit 0
fi

brightness_path=${backlight_path}/brightness
max_bright=$(cat ${backlight_path}/max_brightness)
current=$(cat $brightness_path)

step=$(($max_bright / 100))

if [ "$1" == "up" ]; then
    new=$(($current + $step))
    sudo tee $brightness_path <<<$new
elif [ "$1" == "down" ]; then
    new=$(($current - $step))
    echo $((new < 0))
    if (($new < 0)); then
        new=1
    fi

    sudo tee $brightness_path <<<$new
elif [ "$1" == "normal" ]; then
    new=$(($max_bright / 2))
    sudo tee $brightness_path <<<$new
elif [ "$1" == "max" ]; then
    sudo tee $brightness_path <<<$max_bright
else
    re='^[0-9]'
    if ! [[ $1 =~ $re ]]; then
        echo "error: Not a number" >&2
        exit 1
        exit 1
    fi
    sudo tee $brightness_path <<<$1
fi
