#!/bin/bash
save_dir=$HOME/.local/share/cataclysm-dda


if [ ! -d "$save_dir" ]; then
    mkdir -p $save_dir
fi

if [ "$1" == "save" ]; then
    echo "$(date +'%T') Saving"
    # Remove previous save hot-backup
    rm -rf $save_dir/save-bak
    # Create new hot-backup
    cp -r $save_dir/save $save_dir/save-bak

    # Create permanent backup
    name=$(date +%Y-%m-%d-%H%M%S_save)
    mkdir -p $save_dir/backup/
    tar -I zstd -cf $save_dir/backup/$name.tar.zst -C $save_dir ./save

elif [ "$1" == "restore" ]; then
    echo "$(date +'%T') Restoring save"

    # Restore previous hot-backup
    rm -rf $save_dir/save
    cp -r $save_dir/save-bak $save_dir/save
else
    echo "$(date +'%T') Starting game. Other valid commands are 'save' and 'restore'"
fi

cataclysm-tiles

exit 0
