#!/bin/bash
rm -rf ~/Desktop
rm -rf ~/Documents

# Cache stuff
rm -rf ~/.ansible
rm -rf ~/.pkg-cache
rm -rf ~/.cmake
rm -rf ~/.subversion
rm -rf ~/.dotnet
rm -rf ~/.ipfs
rm -rf ~/.nuget
rm -rf ~/.mono
rm -rf ~/.berkshelf

# History stuff
rm -rf ~/.wget-hsts
rm -rf ~/.NERDTreeBookmarks
rm -rf ~/.bash_history
rm -rf ~/.python_history
rm -rf ~/.putty

# Java stuff
rm -rf ~/.java
rm -rf ~/.gradle
rm -rf ~/.rye

# Wtf
rm -rf ~/.esd_auth
rm -rf ~/.sbd
rm -rf ~/GPUCache
rm -rf ~/.gnome
rm -rf ~/.android

# Desktop/File manager
rm -rf ~/.local/share/Trash/*
rm -rf ~/Desktop
