#!/bin/bash
set -euo pipefail

cwd=$(pwd)

for folder in *; do
    cd "${cwd}/${folder}"
    mogrify -format png *.jpg
    mogrify -format png *.JPEG
    mogrify -format png *.JPG
    rm -f *.jpg *.JPEG *.JPG
done
