#!/bin/bash
set -euo pipefail

topic=$1
year=$(date +"%Y")
dir=~/Syncthing/Tagebuch/normal/$year

if [ -z $topic ]; then
    filename="$(date -d "now - 6 hours" +'%Y-%m-%d')"
else
    filename="$(date -d "now - 6 hours" +'%Y-%m-%d')_$topic"
fi

mkdir -p $dir

vim $dir/$filename
