#!/bin/bash
set -euo pipefail

year=$(date +"%Y")
dir=~/Dokumente/Various/Tagebuch/$year

if [ -z "${1+x}" ]; then
    filename="$(date -d "now - 6 hours" +'%Y-%m-%d')"
else
    filename="$(date -d "now - 6 hours" +'%Y-%m-%d')_${1}"
fi

mkdir -p "$dir"

vim "$dir/$filename"
