#!/bin/bash
# First parameter: New file names, for instance, `test`
# Second parameter: If provided, this will be the new file extension `.jpg`
# Example: `folder-rename test .jpg` would result in => test1.jpg, test2.jpg..

if [ -n "$1" ]; then
    echo "Rename all files in a directory"
    echo ""
    echo "New Name:" $1
    count=1
    seperator="."

    for file in *
    do
        # Creating new file name, indices smaller than 10 will become 01-09
        if [ $count -lt 10 ]; then
            name="${1}0$count"
        else
            name=$1$count
        fi

        # Get the current file extension
        extension="${file##*.}"
        if [ -z "$2" ] ; then
            echo "moving $file to ${name}$seperator$extension"
            mv $file ${name}.$extension
        elif [ "dry" = "$2" ] ; then
            echo "moving $file to ${name}$seperator$extension"
        else
            echo "moving $file to $name.$2"
            mv $file ${name}.$2
        fi
        # If a third parameter is provided, this script will perform a dry run
        # Second parameter becomes file ending
        # Incrementing counter
        ((count++))
    done
else
    echo "Please enter a new name for those files"
fi

