#!/bin/bash
# Check all hard drives and display critical device stats.

# Get all HDD devices
devices=$(lsblk -d -o NAME -n)

for device in $devices; do
    echo "Checking $device"
    smartctl -a "/dev/$device" | grep -e self-assessment \
        -e Raw_Read_Error_Rate \
        -e Reallocated_Sector_Ct \
        -e Current_Pending_Sector \
        -e Offline_Uncorrectable \
        -e Power_On_Hours
    echo ""
done
