#!/bin/bash
set -euo pipefail

language=$1
languages="de eu state toggle"

state_file="${XDG_RUNTIME_DIR}"/keyboard_layout

if [[ ! " ${languages} " == *" $1 "* ]]; then
    echo "Invalid subcommand."
    echo "Valid subcommands are: $languages"
    exit 1
fi

if [ "${language}" == "state" ]; then
    if [ ! -f $state_file ]; then
        state="eu"
    else
        state="$(cat $state_file)"
    fi
    echo "{\"icon\":\"keyboard\", \"text\": \"${state}\"}"
elif [ "${language}" == "de" ]; then
    hyprctl keyword input:kb_layout de >/dev/null
    hyprctl keyword input:kb_options caps:escape >/dev/null

    echo 'de' >$state_file
elif [ "${language}" == "eu" ]; then
    hyprctl keyword input:kb_layout eu >/dev/null
    hyprctl keyword input:kb_model altg_weur >/dev/null
    hyprctl keyword \
        input:kb_options \
        caps:escape,lv3:ralt_switch,altwin:swap_lalt_lwin \
        >/dev/null

    echo 'eu' >$state_file
elif [ "${language}" == "toggle" ]; then
    # Toggle to the other language, depending on the current layout
    # If no state file exists, switch to de
    if [ ! -f $state_file ]; then
        hypr-keyboard-layout de
    elif [ "$(cat $state_file)" == "de" ]; then
        hypr-keyboard-layout eu
    else
        hypr-keyboard-layout de
    fi
fi
