#!/bin/bash
set -euo pipefail

file1="/tmp/i3lock-blur.png"
file2="/tmp/i3lock-blur_temp.png"

scrot -d0 -o "$file1"
convert "$file1" -filter Point -resize 20% "$file1"
convert "$file1" -filter Point -resize 500% "$file2"
i3lock -e -i $file2
rm "$file1" "$file2"
