#!/bin/bash
set -euo pipefail

language=$1
languages="de en toggle"

state_file="${XDG_RUNTIME_DIR}"/keyboard_layout

if [[ ! " ${languages} " == *" $1 "* ]]; then
    echo "Invalid language."
    echo "Valid languages are: $languages"
    exit 1
fi

if [ "${language}" == "de" ]; then
    setxkbmap -layout de \
        -option caps:escape

    echo 'de' >$XDG_RUNTIME_DIR
    echo '{"icon":"keyboard","state":"Idle", "text": " de"}'
elif [ "${language}" == "en" ]; then
    setxkbmap \
        -layout arne \
        -variant altgr-weur \
        -option caps:escape \
        -option lv3:ralt_switch \
        -option altwin:swap_lalt_lwin

    echo 'en' >$XDG_RUNTIME_DIR
    echo '{"icon": "keyboard","state": "Idle", "text": " en"}'

elif [ "${language}" == "toggle" ]; then
    # Toggle to the other language, depending on the current layout
    # If no state file exists, switch to de
    if [ ! -f $FILE ]; then
        ~/.bin/keyboard-layout de
    elif [ "$(cat $state_file)" == "de" ]; then
        ~/.bin/keyboard-layout en
    else
        ~/.bin/keyboard-layout de
    fi
fi
