#!/bin/bash
# Rename a i3 workspace from $1 to $2

if [ -z "$1" ]; then
    echo "Two arguments needed"
elif [ -z "$2" ]; then
    echo "Two arguments needed"
else
    command="rename workspace $1 to $2"
    echo $command
    swaymsg $command
fi
