#!/bin/env bash

# Literally that, nuke the postgres data folder and create it anew

read -p "Are you sure? (y/n): " choice
case "$choice" in
y | Y) echo ;;
*) exit 1 ;;
esac

read -p "Like, are you sure you wanna nuke the DB? (YES/n): " choice
case "$choice" in
YES) echo ;;
*) exit 1 ;;
esac

echo "Stopping postgres"
sudo systemctl stop postgresql
echo "Nuke and re-initialize postgres data folder"
sudo rm -rf /var/lib/postgres/data
sudo -u postgres initdb -D /var/lib/postgres/data --data-checksums --encoding=UTF8

echo "Starting postgres"
sudo systemctl start postgresql

echo "Create Superuser nuke"
sudo -u postgres createuser -s nuke
echo "Create DB nuke"
createdb nuke
