#!/bin/bash

# Takes some file and reencodes it with sensible defaults to ~/ as mp4 with h.265

set -euo pipefail

original_path=$1
filename=$(basename -- "$original_path")
filename="${filename%.*}"
destination_path=~/reencodes/$filename.mp4

mkdir -p ~/reencodes

nice -n 15 ffmpeg \
    -i $original_path \
    -map 0:v:0 \
    -map 0:a:0 \
    -sn \
    -dn \
    -c:a aac \
    -b:a 128k \
    -c:v libx265 \
    -preset slower \
    -x265-params \
    -crf=19:pools=none \
    -threads "$(nproc --all)" \
    $destination_path
