#!/bin/bash

# Opens a new neovim in alacritty

project_dirs=`
    f find-repos \
        /home/nuke/repos \
        /home/nuke/.dotfiles \
        /home/nuke/work \
        --exclude \
        /home/nuke/repos/archive \
`
IFS=$'\n' project_dirs=($project_dirs)
project_dir_names=`
    f find-repos \
        --basename \
        /home/nuke/repos \
        /home/nuke/.dotfiles \
        /home/nuke/work \
        --exclude \
        /home/nuke/repos/archive \
`
#printf '%s\n' "${project_dirs[@]}"
#echo $project_dir_names;

# `-no-custom` Don't allow custom inputs
# `-i` case insensitive
# `-p` Prompt that's displayed next to the search bar
# `-format` defined the actual output format, 'i' returns just the selected index.
selected_directory_index=$(echo "$project_dir_names" | rofi -dmenu -no-custom -i -p "nvim" -format 'i')

if [[ $? -ne 0 ]]; then
    echo "No element selected. Rofi exited early"
    exit 0
fi

echo $selected_directory_index
echo "${project_dirs[$selected_directory_index]}"

set -o allexport
ROFI_COMMAND="nvim"
alacritty \
    --working-directory "${project_dirs[$selected_directory_index]}" \
    --command "zsh"
