#!/bin/bash
# Rotate:
#
# ffmpeg -i in.mov -vf "transpose=1" out.mov
#
# For the transpose parameter you can pass:
#
# 0 = 90CounterCLockwise and Vertical Flip (default)
# 1 = 90Clockwise
# 2 = 90CounterClockwise
# 3 = 90Clockwise and Vertical Flip
#
# Use -vf "transpose=2,transpose=2" for 180 degrees.

file=$2

if [ "$1" == "left" ]; then
    direction="transpose=2"
elif [ "$1" == "right" ]; then
    direction="transpose=1"
elif [ "$1" == "down" ]; then
    direction="transpose=2,transpose=2"
fi

basename=$(basename -- "$file")
extension="${basename##*.}"
filename="${basename%.*}"

temp_file="${filename}-temp.${extension}"

rotate_command="ffmpeg -i $file -vf $direction $temp_file"

eval $rotate_command

if [ $? -eq 0 ]; then
    mv $temp_file $file
else
    echo "Errored"
fi

