#!/bin/bash

# Interface that should be spoofed
interface=($(getWlanId))

# Get the current Mac address
ipLinkString=($(ip link show $interface))

count=0
for element in "${ipLinkString[@]}"; do
    if [[ $element == "link/ether" ]]; then
        echo "Old Mac: ${ipLinkString[$count+1]}"
        currentMac="${ipLinkString[$count+1]}"
        break
    fi
    ((++count))
done

# Generating new random mac, first 3 bytes stay the
# same to ensure a correct vendor id
firstMac=$(echo $currentMac | head -c 8 )
lastMac=$(dd bs=1 count=3 if=/dev/random 2>/dev/null |hexdump -v -e '/1 ":%02X"')
mac=$firstMac$lastMac
mac=${mac,,}

# Stopping all networking and setting down interfaces
sudo netctl stop-all
sudo ip link set $interface down
sudo ip link set dev $interface down

# Changing mac address
sudo ip link set dev $interface address $mac

echo "New Mac: $mac"
