#!/bin/bash
set -euo pipefail

language=$1
commands="de eu state toggle"

state_file="${XDG_RUNTIME_DIR}/keyboard_layout"

if [[ ! " ${commands} " == *" $1 "* ]]; then
    echo "Invalid subcommand."
    echo "Valid subcommands are: $commands"
    exit 1
fi

if [ "${language}" == "state" ]; then
    if [ ! -f "$state_file" ]; then
        state="eu"
    else
        state="$(cat "$state_file")"
    fi
    echo "{\"icon\":\"keyboard\", \"text\": \"${state}\"}"
elif [ "${language}" == "de" ]; then
    >&2 echo "Running explicit de command"
    >&2 swaymsg input "type:keyboard" xkb_layout de >/dev/null
    >&2 swaymsg input "type:keyboard" xkb_options caps:escape >/dev/null

    echo 'de' >"$state_file"
elif [ "${language}" == "eu" ]; then
    >&2 echo "Running explicit eu command"
    >&2 swaymsg input "type:keyboard" xkb_layout eu >/dev/null
    >&2 swaymsg input "type:keyboard" xkb_model altg_weur >/dev/null
    >&2 swaymsg input "type:keyboard" xkb_options caps:escape

    echo 'eu' >"$state_file"
elif [ "${language}" == "toggle" ]; then
    >&2 echo "Running toggle command"
    if [ ! -f "$state_file" ]; then
        >&2 echo "No state file found"
        sway-keyboard-layout de
    elif [ "$(cat "$state_file")" == "de" ]; then
        >&2 echo "Current state language is de"
        sway-keyboard-layout eu
    else
        >&2 echo "Current state language is en"
        sway-keyboard-layout de
    fi
fi
