#!/bin/bash
# A script to sync a remote postgres database to the current machine
set -euo pipefail
host=$1
database=$2

echo 'Dumping DB on remote'
ssh $host "pg_dump -O -F c ${database} > ${database}.dump"
echo 'Sync DB'
scp $host:$database.dump /tmp/

echo 'Drop and recreate DB'
dropdb $database || true
createdb $database

echo 'Restoring DB'
pg_restore -O -j 4 -F c -d $database /tmp/$database.dump

echo 'Deleting dumps'
rm /tmp/$database.dump
ssh $host "rm ${database}.dump"
echo 'Done'
